supermarket/apps/accounts/urls.py
from django.urls import path
from .views import RegisterUserView,VerifyRegisterUserView,LoginUserView,ChangePasswordView,RememberPasswordView,LogoutUser,UserPanelView,UserPanelOrdersView,UserUpdateDetail,UserPasswordChange,check_user_name_validation_ajax
app_name='accounts'

urlpatterns = [
    path('register/',RegisterUserView.as_view(),name='register'),
    path('verify/',VerifyRegisterUserView.as_view(),name='verify'),
    path('login/',LoginUserView.as_view(),name='login'),
    path('logout/',LogoutUser.as_view(),name='logout'),
    path('change_password/',ChangePasswordView.as_view(),name='changepassword'),
    path('remember_password/',RememberPasswordView.as_view(),name='rememberpassword'),
    path('userpanel/',UserPanelView.as_view(),name='userpanel'),
    path('userpanel_orders/',UserPanelOrdersView.as_view(),name='userpanel_orders'),
    path('userdetail_modify_informations/',UserUpdateDetail.as_view(),name='userdetail_modify_informations'),
    path('userdetail_modify_password/',UserPasswordChange.as_view(),name='userdetail_modify_password'),
    path('username_form_validation/',check_user_name_validation_ajax,name='username_form_validation'),
]

supermarket/supermarket/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.index.urls',namespace='index')),
    path('accounts/', include('apps.accounts.urls',namespace='accounts')),
    path('about_us/',include('apps.about_us.urls',namespace='about_us')),
    path('search/',include('apps.search.urls',namespace='search')),
    path('contact_us/',include('apps.contact_us.urls',namespace='contact_us')),
    path('products/',include('apps.products.urls',namespace='products')),
    path('orders/',include('apps.orders.urls',namespace='orders')),
    path('payments/',include('apps.payments.urls',namespace='payments')),
    path('scoring/',include('apps.scoring.urls',namespace='scoring')),
    path('comments/',include('apps.comments.urls',namespace='comments')),
    path('favorite/',include('apps.favorite.urls',namespace='favorite')),
    path('compare/',include('apps.compare.urls',namespace='compare')),
    path('blogs/',include('apps.blogs.urls',namespace='blogs')),
    path('ckeditor',include('ckeditor_uploader.urls')),




]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

supermarket/templates/account_app/change_password.html
{% extends 'main_template.html' %}
{% block title %}تغییر رمز{% endblock title %}
{% block body %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="">حساب کاربری</a>
									/
								</li>
								<li class="active" aria-current="page"> ایجاد حساب کاربری</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>تغییر رمز عبور حساب کاربری</h1></div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6 d-flex mt-4 mt-md-0">
							<div class="card flex-grow-1 mb-0">
								<div class="card-body">
									<h3 class="card-title">تغییر رمز عبور</h3>

                                    <form action="" method="post">
                                        {% csrf_token %}
                                        {{change_password.as_p}}
										<button type="submit" class="btn btn-primary mt-4">ثبت تغییرات</button>
                                    </form>

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->

{% endblock body %}

supermarket/templates/account_app/login_user_form.html
{% extends 'main_template.html' %}
{% block title %}home{% endblock title %}
{% block body %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="#">حساب کاربری</a>
									/
								</li>
								<li class="active" aria-current="page">ورود به حساب کاربری</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>ورود به حساب کاربری</h1>
					</div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6">
							<div class="card flex-grow-1 mb-md-0">
								<div class="card-body">
									<h3 class="card-title">ورود</h3>
									<form action="" method='post'>
                                        {% csrf_token %}
                                        {{login_form.as_p}}
										<div>
											<a href=" {% url 'accounts:rememberpassword' %} ">فراموشی رمز عبور</a>
										</div>
										<button type="submit" class="btn bg-primary text-light mt-4">ورود</button>
										
										<div class="form-group">
											<div class="form-check"><span class="form-check-input input-check"><span class="input-check__body"><input class="input-check__input" type="checkbox" id="login-remember"> <span class="input-check__box"></span>
												<svg class="input-check__icon" width="9px" height="7px">
													<use xlink:href="images/sprite.svg#check-9x7"></use>
												</svg>
												</span>
												</span>
												<label class="form-check-label" for="login-remember">به خاطر سپاری</label>
											</div>
										</div>

									</form>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<!-- end site__body -->

{% endblock body %}

supermarket/templates/account_app/order_history.html
{% extends 'account_app/user_panel.html' %}
{% load render_partial %}
{% block dashbord %}

<div class="card">
    <div class="card-header">
        <h5>سابقه خرید</h5></div>
    <div class="card-divider"></div>
    <div class="card-table">
        <div class="table-responsive-sm">
            <table>
                <thead>
                    <tr>
                        <th>سفارش</th>
                        <th>تاریخ</th>
                        <th>وضعیت</th>
                        <th>جمع کل</th>
                    </tr>
                </thead>
                <tbody>
                    {% comment %} {% for order in user_orders %} {% endcomment %}
                        <tr>
                            <td><a href="">{{order}}</a></td>
                            <td>2 فروردین 1401</td>
                            <td>در حال پردازش</td>
                            <td>2,425,000 تومان برای 5 محصول</td>
                        </tr>
                    {% comment %} {% endfor %} {% endcomment %}

                    {% comment %} <tr>
                        <td><a href="">#7592</a></td>
                        <td>28 فروردین 1401</td>
                        <td>در حال پردازش</td>
                        <td>325,000 تومان برای 3 محصول</td>
                    </tr>
                    <tr>
                        <td><a href="">#7192</a></td>
                        <td>15 فروردین 1401</td>
                        <td>ارسال شده</td>
                        <td>1,786,000 تومان برای 4 محصول</td>
                    </tr>
                    <tr>
                        <td><a href="">#6321</a></td>
                        <td>28 فروردین 1401</td>
                        <td>اتمام یافته</td>
                        <td>25,000 تومان برای 1 محصول</td>
                    </tr>
                    <tr>
                        <td><a href="">#6001</a></td>
                        <td>21 فروردین 1401</td>
                        <td>اتمام یافته</td>
                        <td>225,000 تومان برای 2 محصول</td>
                    </tr>
                    <tr>
                        <td><a href="">#4120</a></td>
                        <td>11 فروردین 1401</td>
                        <td>اتمام یافته</td>
                        <td>4,485,000 تومان برای 7 محصول</td>
                    </tr> {% endcomment %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-divider"></div>
    <div class="card-footer">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link page-link--with-arrow" href="" aria-label="Previous">
                    <svg class="page-link__arrow page-link__arrow--left" aria-hidden="true" width="8px" height="13px">
                        <use xlink:href="images/sprite.svg#arrow-rounded-left-8x13"></use>
                    </svg>
                </a>
            </li>
            <li class="page-item"><a class="page-link" href="">1</a></li>
            <li class="page-item active"><a class="page-link" href="">2 <span class="sr-only">(کنونی)</span></a></li>
            <li class="page-item"><a class="page-link" href="">3</a></li>
            <li class="page-item">
                <a class="page-link page-link--with-arrow" href="" aria-label="Next">
                    <svg class="page-link__arrow page-link__arrow--right" aria-hidden="true" width="8px" height="13px">
                        <use xlink:href="images/sprite.svg#arrow-rounded-right-8x13"></use>
                    </svg>
                </a>
            </li>
        </ul>
    </div>
</div>


{% endblock dashbord %}

supermarket/templates/account_app/register_user_form.html
{% extends 'main_template.html' %}
{% block title %}home{% endblock title %}
{% block body %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="">حساب کاربری</a>
									/
								</li>
								<li class="active" aria-current="page"> ایجاد حساب کاربری</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>ایجاد حساب کاربری جدید</h1></div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6 d-flex mt-4 mt-md-0">
							<div class="card flex-grow-1 mb-0">
								<div class="card-body">
									<h3 class="card-title">ثبت نام</h3>

                                    <form action="" method="post" id="register_form">
										<div id="register_form_message" class="pl-2 bg-light rounded-pill"></div>
                                        {% csrf_token %}
                                        {{register_form.as_p}}
										<button type="submit" class="btn btn-primary mt-4">ثبت نام</button>
                                    </form>

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->

{% endblock body %}

supermarket/templates/account_app/remember_password.html
{% extends 'main_template.html' %}
{% block title %}اهراز هویت{% endblock title %}
{% block body %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="#">حساب کاربری</a>
									/
								</li>
								<li class="active" aria-current="page">احراز هویت</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>ارسال شماره موبایل جهت تغییر رمز عبور</h1>
					</div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6">
							<div class="card flex-grow-1 mb-md-0">
								<div class="card-body">

									<form action="" method="post">
                                        {% csrf_token %}
                                        {{remember_password.as_p}}
										<button type="submit" class="btn btn-primary mt-4">ارسال</button>
                                    </form>

								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->
{% endblock body %}

supermarket/templates/account_app/user_panel.html
{% extends 'main_template.html' %}
{% block title %}پنل کاربری{% endblock title %}
{% block body %}
   <div class="site__body">
    <div class="page-header">
        <div class="page-header__container container">
            <div class="page-header__breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="../index.html">خانه</a>
                            /
                        </li>
                        <li class="breadcrumb-item"><a href="">داشبورد</a>
                        </li>
                        
                    </ol>
                </nav>
            </div>
            <div class="page-header__title">
                <h1>حساب کاربری</h1></div>
        </div>
    </div>
    <div class="block">
        <div class="container">
            <div class="row">
                <div class="col-12 col-lg-3 d-flex">
                    <div class="account-nav flex-grow-1">
                        <h4 class="account-nav__title">ناوبری</h4>
                        <ul>
                            {% comment %} account-nav__item--active {% endcomment %}
                            <li class="account-nav__item "><a href=" {% url 'accounts:userpanel' %}">داشبورد</a></li>
                            <li class="account-nav__item"><a  href=" {% url 'accounts:userdetail_modify_informations' %} ">ویرایش پروفایل</a></li>
                            <li class="account-nav__item"><a  href=" {% url 'accounts:userpanel_orders' %} ">سابقه خرید</a></li>
                            <li class="account-nav__item"><a  href=" {% url 'accounts:userdetail_modify_password' %} ">تغییر رمز عبور</a></li>
                            <li class="account-nav__item"><a href=" {% url 'accounts:logout' %} ">خروج</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-12 col-lg-9 mt-4 mt-lg-0">

                {% block dashbord %}{% endblock dashbord %}

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

supermarket/templates/account_app/verify_register_form.html
{% extends 'main_template.html' %}
{% block title %}اهراز هویت{% endblock title %}
{% block body %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href="#">حساب کاربری</a>
									/
								</li>
								<li class="active" aria-current="page">احراز هویت</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>تایید شماره موبایل</h1>
					</div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6">
							<div class="card flex-grow-1 mb-md-0">
								<div class="card-body">

									<form action="" method="post">
                                        {% csrf_token %}
                                        {{verify_register_form.as_p}}
										<button type="submit" class="btn btn-primary mt-4">ارسال کد</button>
                                    </form>

								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->
{% endblock body %}