supermarket/apps/products/urls.py
from django.urls import path
from .views import cheapest_product,newest_product,favorite_product,related_product,ProductGroupView,ProductDetailView,get_product_group_filter,get_brand,get_other_features_for_each_group,ProductByGroupView,topsell_product
app_name='products'

urlpatterns = [
    path('cheapest_product/',cheapest_product,name='cheapest_product'),
    path('newest_product/',newest_product,name='newest_product'),
    path('topsell_product/',topsell_product,name='topsell_product'),
    path('favorite_product/',favorite_product,name='favorite_Product'),
    path('related_product/<slug:slug>/',related_product,name='related_product'),
    path('product_group/',ProductGroupView.as_view(),name='product_group'),
    path('product_detail/<slug:slug>/',ProductDetailView.as_view(),name='product_detail'),
    path('product_groups_partial/',get_product_group_filter,name='product_groups_partial'),
    path('product_groups_brand/<slug:slug>',get_brand,name='product_groups_brand'),
    path('product_other_filter/<slug:slug>',get_other_features_for_each_group,name='product_other_filter'),
    path('products_by_group/<slug:slug>',ProductByGroupView.as_view(),name='products_by_group'),
]

supermarket/supermarket/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.index.urls',namespace='index')),
    path('accounts/', include('apps.accounts.urls',namespace='accounts')),
    path('about_us/',include('apps.about_us.urls',namespace='about_us')),
    path('search/',include('apps.search.urls',namespace='search')),
    path('contact_us/',include('apps.contact_us.urls',namespace='contact_us')),
    path('products/',include('apps.products.urls',namespace='products')),
    path('orders/',include('apps.orders.urls',namespace='orders')),
    path('payments/',include('apps.payments.urls',namespace='payments')),
    path('scoring/',include('apps.scoring.urls',namespace='scoring')),
    path('comments/',include('apps.comments.urls',namespace='comments')),
    path('favorite/',include('apps.favorite.urls',namespace='favorite')),
    path('compare/',include('apps.compare.urls',namespace='compare')),
    path('blogs/',include('apps.blogs.urls',namespace='blogs')),
    path('ckeditor',include('ckeditor_uploader.urls')),




]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

supermarket/templates/product_app/partials/brand_list.html
<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
        <div class="block block-features block-features--layout--boxed">
            <div class="block-header">
                <h3 class="block-header__title">لیست برند ها</h3>
                <div class="block-header__divider"></div>
                <div class="block-header__arrows-list">
                </div>
            </div>
        <div class="container text-center">
            <div class="d-flex flex-wrap justify-content-center">
                {% for brand in brands %}
                    <div class="col-md-3 col-sm-8 text-center m-3 border border-pill ">
                        <img src="{{media_url}}{{brand.brand_image}}" alt="" style="width:100%;">
                    </div>
                    <div class="block-features__divider"></div>
                {% endfor %}
            </div>
        </div>
        <br>
            </div>
        </div>
    </div>
</div>

supermarket/templates/product_app/partials/cheapest_product.html
{% include 'product_app/partials/product_box.html' with type=1 %}

supermarket/templates/product_app/partials/favorite_product.html
<div class="block block--highlighted block-categories block-categories--layout--compact">
    <div class="container">
        <div class="block-header">
            <h3 class="block-header__title">دسته های محبوب</h3>
            <div class="block-header__divider"></div>
        </div>
        <div class="block-categories__list">
            {% for group in product_group %}
            <div class="block-categories__item category-card category-card--layout--compact">
                <div class="category-card__body">
                    <div class="category-card__image">
                        <a 
                        href="{% url 'products:products_by_group' slug=group.group_slug %} ">
                            <img src="{{media_url}}{{group.group_image}}" alt="">
                        </a>
                    </div>
                    <div class="category-card__content">
                        <div class="category-card__name">
                            <a href="{% url 'products:products_by_group' slug=group.group_slug %}">
                            {{group.group_name}}
                        </a>
                        </div>
                        <div class="category-card__products">{{group.product_count }} محصول</div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <a href=" {% url 'products:product_group' %} ">نمایش همه دسته ها</a>
        </div>
    </div>
</div>

supermarket/templates/product_app/partials/newest_product.html
{% include 'product_app/partials/product_box.html' with type=2 %}

supermarket/templates/product_app/partials/product_brand_filter.html
<div class="widget-filters__item">
    <div class="filter filter--opened" data-collapse-item>
        <button type="button" class="filter__title" data-collapse-trigger>برند
            <svg class="filter__arrow" width="12px" height="7px">
                <use xlink:href="images/sprite.svg#arrow-rounded-down-12x7"></use>
            </svg>
        </button>
        <div class="filter__body" data-collapse-content>
            <div class="filter__container">
                <div class="filter-list">
                    <div class="filter-list__list">

                        {% for brand in brands %}
                            <label class="filter-list__item"><span class="filter-list__input input-check">
                                <span class="input-check__body">
                                <input id="item_{{brand.id}}" class="input-check__input" name="brand" value="{{brand.id}}" type="checkbox"> 
                                <span class="input-check__box"></span>
                                <svg class="input-check__icon" width="9px" height="7px">
                                    <use xlink:href="images/sprite.svg#check-9x7"></use>
                                </svg>
                                </span>
                                </span><span class="filter-list__title">{{brand.brand_name}} </span><span class="filter-list__counter"></span>
                            </label>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

supermarket/templates/product_app/partials/product_group.html
<div class="block-header">
    <h3 class="block-header__title">{{title}}</h3>
    <div class="block-header__divider"></div>
    <ul class="block-header__groups-list">
        <li>
            <button type="button"   id="bn_0"
                class="block-header__group block-header__group--active" onclick="change_group_{{fun_val}}(0)">همه</button>
        </li>
        {% for group in product_group %}
            <li>
                <button type="button" id="bn_{{group.id}}" class="block-header__group" onclick="change_group_{{fun_val}}({{group.id}})">{{group.group_name}}</button>
            </li>
        {% endfor %}
    </ul>
    <div class="block-header__arrows-list">
        <button class="block-header__arrow block-header__arrow--left" type="button">
            <i class="fas fa-angle-right"></i>
        </button>
        <button class="block-header__arrow block-header__arrow--right" type="button">
            <i class="fas fa-angle-left"></i>
        </button>
    </div>
</div>

supermarket/templates/product_app/partials/product_group_filter.html
<div class="widget-filters__item">
    <div class="filter filter--opened" data-collapse-item>
        <button type="button" class="filter__title" data-collapse-trigger>دسته ها
        <svg class="filter__arrow" width="12px" height="7px">
        <use xlink:href="images/sprite.svg#arrow-rounded-down-12x7"></use>
        </svg>
        </button>
        <div class="filter__body" data-collapse-content>
            <div class="filter__container">
                <div class="filter-categories">
                    <ul class="filter-categories__list">
                        {% for group in product_groups %}
                            <li class="filter-categories__item filter-categories__item--parent">
                                <svg class="filter-categories__arrow" width="6px" height="9px">
                                    <use xlink:href="images/sprite.svg#arrow-rounded-left-6x9"></use>
                                </svg> 
                                <a href=" {% url 'products:products_by_group' slug=group.group_slug %} ">{{group.group_name}}</a>
                                <div class="filter-categories__counter">
                                    {{group.count}}
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

supermarket/templates/product_app/partials/product_other_filter.html
{% for key,val in feature_list_dic.items %}
    {% if val %}
        <div class="widget-filters__item">
            <div class="filter filter--opened" data-collapse-item>
                <button type="button" class="filter__title" data-collapse-trigger>{{key}}
                    <svg class="filter__arrow" width="12px" height="7px">
                        <use xlink:href="images/sprite.svg#arrow-rounded-down-12x7"></use>
                    </svg>
                </button>
                <div class="filter__body" data-collapse-content>
                    <div class="filter__container">
                        <div class="filter-list">
                            <div class="filter-list__list">

                            {% for item in val %}
                                <label class="filter-list__item"><span class="filter-list__input input-check">
                                    <span class="input-check__body">
                                    <input id="item_{{item.id}}" class="input-check__input" name="{{key.feature_slug}}" value="{{item.id}}" type="checkbox"> 
                                    <input id="item_{{item.id}}" class="input-check__input" name="feature" value="{{item.id}}" type="checkbox"> 
                                    <span class="input-check__box"></span>
                                    <svg class="input-check__icon" width="9px" height="7px">
                                        <use xlink:href="images/sprite.svg#check-9x7"></use>
                                    </svg>
                                    </span>
                                    </span><span class="filter-list__title">{{item.value_title}} </span><span class="filter-list__counter"></span>
                                </label>
                            {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}

supermarket/templates/product_app/partials/product_price_filter.html
{% load humanize %}

<div class="widget-filters__item">
    <div class="filter filter--opened" data-collapse-item>
        <button type="button" class="filter__title" data-collapse-trigger>قیمت
            <svg class="filter__arrow" width="12px" height="7px">
                <use xlink:href="images/sprite.svg#arrow-rounded-down-12x7"></use>
            </svg>
        </button>
        <div class="filter__body" data-collapse-content>
            <div class="filter__container">
                <div class="filter-price" data-min="5000" data-max="150000" data-from="25000" data-to="110000">
                    <div class="filter-price__slider"></div>
                    <div class="filter-price__title">
                        {% if cur_prices %}
                            <span class="filter-price__min-value" id='cur_price'>{{cur_prices |intcomma }}</span> تومان 
                        {% else %}
                            <span class="filter-price__min-value" id='cur_price'>{{res_aggre.max_price |intcomma }}</span> تومان 
                        {% endif %}
                        <br>
                        {% if cur_prices %}
                            <input type="range" name='price' min={{res_aggre.min_price}} max={{res_aggre.max_price}} value={{cur_prices}} oninput="showVal(this.value)"  style='width:200px;'><br>
                        {% else %}
                            <input type="range" name='price' min={{res_aggre.min_price}} max={{res_aggre.max_price}} value={{res_aggre.max_price}} oninput="showVal(this.value)"  style='width:200px;'><br>
                        {% endif %}
                        <span>{{res_aggre.min_price |intcomma }}</span> تومان
                        &nbsp;&nbsp;
                        <span>{{res_aggre.max_price |intcomma }}   تومان</span>

                        <span class="filter-price__max-value"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

supermarket/templates/product_app/partials/related_product.html
<div class="block block-products-carousel" data-layout="grid-5">
    <div class="container">
        {% include 'product_app/partials/product_group.html' with title='محصولات مرتبط' %}
        {% include 'product_app/partials/product_box.html' with type=3 %}
        <br>
        <br>
        <hr>
            </div>
        </div>
    </div>
</div>

supermarket/templates/product_app/partials/topsell_product.html
{% include 'product_app/partials/product_box.html' with type=1 %}